# Generated by Django 4.0.1 on 2022-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPesticideModels',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('technical_name', models.CharField(max_length=100)),
                ('type_of_pesticide', models.CharField(max_length=100)),
                ('crop', models.TextField()),
                ('diseases', models.TextField()),
                ('dosage_per_ace', models.CharField(max_length=100)),
                ('dialution_period', models.CharField(max_length=100)),
                ('waiting_period', models.CharField(max_length=100)),
                ('area_of_orgin', models.CharField(max_length=100)),
                ('sold_by', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('benefits', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'pesticide_details',
            },
        ),
        migrations.CreateModel(
            name='PesticideDealerModel',
            fields=[
                ('pesticide_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('licence_no', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'pesticide_dealer_details',
            },
        ),
    ]
