# Generated by Django 4.0.1 on 2022-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticidedealerapp', '0002_alter_addpesticidemodels_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpesticidemodels',
            name='pesticide_id',
            field=models.IntegerField(null=True),
        ),
    ]
