# Generated by Django 4.0.1 on 2022-03-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizerapp', '0002_alter_addfertilizermodel_benifits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfertilizermodel',
            name='fertilizer_id',
            field=models.IntegerField(null=True),
        ),
    ]
