# Generated by Django 4.0.1 on 2022-03-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SevamemberModel',
            fields=[
                ('sevamember_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sevamember_details',
            },
        ),
    ]
