# Generated by Django 4.0.1 on 2022-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedDealerModel',
            fields=[
                ('seed_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('licence_no', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'seed_dealer_details',
            },
        ),
        migrations.CreateModel(
            name='SeedVarietiesModel',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('seed_yeid', models.CharField(max_length=100)),
                ('plant_height', models.CharField(max_length=100)),
                ('maturity', models.CharField(max_length=100)),
                ('area', models.TextField()),
            ],
            options={
                'db_table': 'seed_varieties',
            },
        ),
    ]
