# Generated by Django 4.0.1 on 2022-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeddealerapp', '0002_alter_seedvarietiesmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedvarietiesmodel',
            name='seed_id',
            field=models.IntegerField(null=True),
        ),
    ]
