# Generated by Django 4.0.1 on 2022-03-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeddealerapp', '0003_seedvarietiesmodel_seed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedvarietiesmodel',
            name='sold_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seedvarietiesmodel',
            name='technical_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
