# Generated by Django 4.0.1 on 2022-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerComplaintModel',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('complaint', models.TextField()),
            ],
            options={
                'db_table': 'farmer_complaint_details',
            },
        ),
        migrations.CreateModel(
            name='FarmerFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'farmer_feedback_details',
            },
        ),
        migrations.CreateModel(
            name='FarmerHelpModel',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('passbook_No', models.BigIntegerField()),
                ('help', models.TextField(max_length=100)),
                ('reply', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'farmer_help_details',
            },
        ),
        migrations.CreateModel(
            name='FarmerModel',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('aadhar', models.BigIntegerField()),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'farmer_details',
            },
        ),
    ]
